export const CHANGE_SEARCH_ID = 'CHANGE_SEARCH_ID';
export const CHANGE_FAILED_ATTEMPTS = 'CHANGE_FAILED_ATTEMPTS';
export const SET_SEARCH_FAILED = 'SET_SEARCH_FAILED';

export const UPDATE_TICKETS = 'UPDATE_TICKETS';
export const CHANGE_FILTER = 'CHANGE_FILTER';
export const CHANGE_SORTING = 'CHANGE_SORTING';
